### ISSUE TITLE
Scimax issue with encoding in org-mode

### ISSUE THREAD

**Issue by alaskamike** [jkitchin/scimax#317]
I am using scimax with emacs 26.1 on Windows, with Python 3.7.4 manually installed (not Anaconda).  I am working through a tutorial on NLP.  The code runs as a .py file, but doesn't run as an org-mode file (.org):

Code block:

#+BEGIN_SRC ipython :session
processed_comments = []
for sentence in range(0, len(comments)):
    print(sentence)
    # Remove all the special characters
    processed_feature = re.sub(r'\W', ' ', str(comments[sentence]))
    # remove all single characters
    processed_feature= re.sub(r'\s+[a‐zA‐Z]\s+', ' ', processed_feature)
    # Remove single characters from the start
    processed_feature = re.sub(r'\^[a‐zA‐Z]\s+', ' ', processed_feature)
    # Substituting multiple spaces with single space
    processed_feature = re.sub(r'\s+', ' ', processed_feature, flags=re.I)
    # Removing prefixed 'b'
    processed_feature = re.sub(r'^b\s+', '', processed_feature)
    # Converting to Lowercase
    processed_feature = processed_feature.lower()
    processed_comments.append(processed_feature)
#+END_SRC

generates the following error:
Traceback (most recent call last):
  File "c:/Users/mike/.emacs.d/ob-ipython-upstream/client.py", line 64, in <module>
    msgid = c.execute(sys.stdin.read(), allow_stdin=False)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\blocking\client.py", line 43, in wrapped
    msg_id = meth(self, *args, **kwargs)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\client.py", line 254, in execute
    self.shell_channel.send(msg)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\blocking\channels.py", line 88, in send
    self.session.send(self.socket, msg)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\session.py", line 625, in serialize
    content = self.pack(content)
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "c:\Users\mike\AppData\Local\Programs\Python\Python37\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc90' in position 285: surrogates not allowed

**Comment by jkitchin** [comment]
I am not sure how to debug this for you, can you attach a self-contained .py file that works and has that character code in it? I can't reproduce it otherwise.

**Comment by jkitchin** [comment]
I wasn't able to reproduce this on python 3.6 on a Mac.  the last code block just printed integers from 0 to 14639 for me. I am going to be away for the next few days, so maybe I will get a chance to look deeper next week.

**Comment by alaskamike** [comment]
Ok.  Thanks.  I will also try updating my scimax and see if that does anything.

**Comment by alaskamike** [comment]
The code ran fine on Linux, but still fails even on a clean install of
scimax on Windows.

**Comment by jkitchin** [comment]
I think the problem here is in this line: #data_source_url = "https://raw.githubusercontent.com/kolaveridi/kaggle‐Twitter‐US‐Airline‐Sentiment‐/master/Tweets.csv"

The - in that seem to be non-ascii, in fact they don't even resolve to a URL! I think if you delete that line, then everything works for me.

**Comment by alaskamike** [comment]
I was able to resolve it on my computer by resaving the CSV and rerunning
the org-mode file.  I think that original file encoding caused emacs to
have an issue.
Thanks for the help!
