### ISSUE TITLE
Error `500 Internal Server Error` after nuking ipython

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#89]
Async executing following code block would fail:

```text
#+begin_src ipython :session new
print('test')
#+end_src
```
Here is the traceback:

```text
[[elisp:nuke-ipython]]

[[elisp:org-babel-async-ipython-clear-queue]]

Running: (pythonbabel-zh.org . princess-cardinal-fix-asparagus)
Queue: nil

* *ob-ipython-client-driver*

ERROR:tornado.application:Uncaught exception POST /execute/new (::1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='POST', uri='/execute/new', version='HTTP/1.1', remote_ip='::1', headers={'Mime-Version': '1.0', 'Connection': 'keep-alive', 'Extension': 'Security/Digest Security/SSL', 'Host': 'localhost:9988', 'Accept-Encoding': 'gzip', 'Accept': '*/*', 'User-Agent': 'URL/Emacs', 'Content-Length': '14'})
Traceback (most recent call last):
  File "/home/neoarch/Envs/venv/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 4, in raise_exc_info
  File "/home/neoarch/Envs/venv/lib/python3.6/site-packages/tornado/web.py", line 1669, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/neoarch/.emacs.d/elpa/ob-ipython-20160918.1001/driver.py", line 95, in post
    c = get_client(name)
  File "/home/neoarch/.emacs.d/elpa/ob-ipython-20160918.1001/driver.py", line 68, in get_client
    clients[name] = create_client(name)
  File "/home/neoarch/.emacs.d/elpa/ob-ipython-20160918.1001/driver.py", line 56, in create_client
    cf = find_connection_file('emacs-' + name)
  File "/home/neoarch/Envs/venv/lib/python3.6/site-packages/jupyter_client/connect.py", line 211, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))
OSError: Could not find 'emacs-new' in ['.', '/run/user/1000/jupyter']
ERROR:tornado.access:500 POST /execute/new (::1) 14.22ms

* *ob-ipython-kernel-new*


* *Python*

Jupyter console 5.1.0

Python 3.6.1 (default, Apr 13 2017, 08:50:46) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.



In [1]: python.el: native completion setup loaded

In [2]: 
* *ob-ipython-debug*

HTTP/1.1 500 Internal Server Error
Server: TornadoServer/4.5.1
Content-Type: text/html; charset=UTF-8
Date: Wed, 07 Jun 2017 07:39:30 GMT
Content-Length: 93

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

```

**Comment by et2010** [comment]
I figured it out. `nuke-ipython` and rerun doesn't work. `nuke-ipython`, remove `#+name: ...` line and rerun works.

**Comment by jkitchin** [comment]
I can't reproduce this error. The code block seemed to run fine for me.

I don't know how the name could influence the server error you saw. Do you know what caused the hang in the first place?

**Comment by et2010** [comment]
> I can't reproduce this error. 

What about specifying a name? eg.
``` text
#+name: src-block-1
#+begin_src ipython
print('test')
#+end_src
```

**Comment by jkitchin** [comment]
weird. Your guide works perfectly fine for me.

**Comment by et2010** [comment]
After updating all my packages (including packages of arch linux, python, and emacs), even deleting the name won't work. It just hangs and nothing I can do about it.

**Comment by jkitchin** [comment]
Odd indeed. I don't have access to a linux machine this week. Next week when I am back I will be using one, so maybe I will find a way to reproduce it then.

**Comment by et2010** [comment]
I found that if there is a dash char in the session name, e.g. `plot-ex-1`, then 100% it will hang. Killing all the kernel processes and rerun won't fix it. If I remove the dash chars in the name, it works fine. Even if it doesn't work, I can simply nuke the processes and rerun, most time this will fix it.

**Comment by jkitchin** [comment]
Nice find! I will add a check to avoid starting sessions with dashes in them.
